// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Coupon
    {
        public Coupon()
        {
            CouponSettings = new HashSet<CouponSetting>();
            DessertOrders = new HashSet<DessertOrder>();
            LessonOrders = new HashSet<LessonOrder>();
            MemberCoupons = new HashSet<MemberCoupon>();
            Promotions = new HashSet<Promotion>();
        }

        public int CouponId { get; set; }
        public int CouponCategoryId { get; set; }
        public int? DiscountGroupId { get; set; }
        public string CouponName { get; set; }
        public string CouponCode { get; set; }
        public int? LimitType { get; set; }
        public int? LimitValue { get; set; }
        public int DiscountType { get; set; }
        public int? DiscountValue { get; set; }
        public DateTime? StartAt { get; set; }
        public DateTime? EndAt { get; set; }
        public int? Expiration { get; set; }
        public DateTime CreateAt { get; set; }
        public bool Status { get; set; }

        public virtual CouponCategory CouponCategory { get; set; }
        public virtual DiscountGroup DiscountGroup { get; set; }
        public virtual ICollection<CouponSetting> CouponSettings { get; set; }
        public virtual ICollection<DessertOrder> DessertOrders { get; set; }
        public virtual ICollection<LessonOrder> LessonOrders { get; set; }
        public virtual ICollection<MemberCoupon> MemberCoupons { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}