// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class CouponSetting
    {
        public int CouponSettingId { get; set; }
        public int? CouponId { get; set; }
        public string CouponSettingName { get; set; }
        public int CouponType { get; set; }
        public int? Qty { get; set; }

        public virtual Coupon Coupon { get; set; }
    }
}