// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Coupons
    {
        public Coupons()
        {
            CouponSettings = new HashSet<CouponSettings>();
            DessertOrders = new HashSet<DessertOrders>();
            LessonOrders = new HashSet<LessonOrders>();
            MemberCoupons = new HashSet<MemberCoupons>();
            Promotions = new HashSet<Promotions>();
        }

        public int CouponId { get; set; }
        public int CouponCategoryId { get; set; }
        public int? DiscountGroupId { get; set; }
        public string CouponName { get; set; }
        public string CouponCode { get; set; }
        public int? LimitType { get; set; }
        public int? LimitValue { get; set; }
        public int DiscountType { get; set; }
        public int? DiscountValue { get; set; }
        public DateTime? StartAt { get; set; }
        public DateTime? EndAt { get; set; }
        public int? Expiration { get; set; }
        public DateTime CreateAt { get; set; }
        public bool Status { get; set; }

        public virtual CouponCategories CouponCategory { get; set; }
        public virtual DiscountGroups DiscountGroup { get; set; }
        public virtual ICollection<CouponSettings> CouponSettings { get; set; }
        public virtual ICollection<DessertOrders> DessertOrders { get; set; }
        public virtual ICollection<LessonOrders> LessonOrders { get; set; }
        public virtual ICollection<MemberCoupons> MemberCoupons { get; set; }
        public virtual ICollection<Promotions> Promotions { get; set; }
    }
}