// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class CouponCategories
    {
        public CouponCategories()
        {
            Coupons = new HashSet<Coupons>();
        }

        public int CouponCategoryId { get; set; }
        public string CouponCategoryName { get; set; }

        public virtual ICollection<Coupons> Coupons { get; set; }
    }
}