// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class DessertOrders
    {
        public DessertOrders()
        {
            DessertOrderDetails = new HashSet<DessertOrderDetails>();
        }

        public int DessertOrderId { get; set; }
        public int MemberId { get; set; }
        public int DessertOrderStatusId { get; set; }
        public int? CouponId { get; set; }
        public DateTime CreateTime { get; set; }
        public string Recipient { get; set; }
        public string RecipientPhone { get; set; }
        public string RecipientAddress { get; set; }
        public int ShippingFee { get; set; }
        public int DessertOrderTotal { get; set; }
        public string DeliveryMethod { get; set; }
        public string Note { get; set; }
        public string DiscountInfo { get; set; }

        public virtual Coupons Coupon { get; set; }
        public virtual OrderStatuses DessertOrderStatus { get; set; }
        public virtual Members Member { get; set; }
        public virtual ICollection<DessertOrderDetails> DessertOrderDetails { get; set; }
    }
}