// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class DessertCart
    {
        public DessertCart()
        {
            DessertCartItems = new HashSet<DessertCartItem>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public int? MemberCouponId { get; set; }
        public int? DiscountPrice { get; set; }

        public virtual MemberCoupon MemberCoupon { get; set; }
        public virtual Member UsernameNavigation { get; set; }
        public virtual ICollection<DessertCartItem> DessertCartItems { get; set; }
    }
}