// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Desserts
    {
        public Desserts()
        {
            DessertCartItems = new HashSet<DessertCartItems>();
            DessertImages = new HashSet<DessertImages>();
            DessertOrderDetails = new HashSet<DessertOrderDetails>();
            DessertTags = new HashSet<DessertTags>();
            DiscountGroupItems = new HashSet<DiscountGroupItems>();
            Discounts = new HashSet<Discounts>();
            Specification = new HashSet<Specification>();
        }

        public int DessertId { get; set; }
        public string DessertName { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime? ScheduledPublishDate { get; set; }

        public virtual Categories Category { get; set; }
        public virtual ICollection<DessertCartItems> DessertCartItems { get; set; }
        public virtual ICollection<DessertImages> DessertImages { get; set; }
        public virtual ICollection<DessertOrderDetails> DessertOrderDetails { get; set; }
        public virtual ICollection<DessertTags> DessertTags { get; set; }
        public virtual ICollection<DiscountGroupItems> DiscountGroupItems { get; set; }
        public virtual ICollection<Discounts> Discounts { get; set; }
        public virtual ICollection<Specification> Specification { get; set; }
    }
}