// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Dessert
    {
        public Dessert()
        {
            DessertCartItems = new HashSet<DessertCartItem>();
            DessertImages = new HashSet<DessertImage>();
            DessertOrderDetails = new HashSet<DessertOrderDetail>();
            DessertTags = new HashSet<DessertTag>();
            DiscountGroupItems = new HashSet<DiscountGroupItem>();
            Discounts = new HashSet<Discount>();
            Specifications = new HashSet<Specification>();
        }

        public int DessertId { get; set; }
        public string DessertName { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime? ScheduledPublishDate { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<DessertCartItem> DessertCartItems { get; set; }
        public virtual ICollection<DessertImage> DessertImages { get; set; }
        public virtual ICollection<DessertOrderDetail> DessertOrderDetails { get; set; }
        public virtual ICollection<DessertTag> DessertTags { get; set; }
        public virtual ICollection<DiscountGroupItem> DiscountGroupItems { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<Specification> Specifications { get; set; }
    }
}