// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class DessertCartItems
    {
        public int Id { get; set; }
        public int DessertCartId { get; set; }
        public int SpecificationId { get; set; }
        public int DessertId { get; set; }
        public string Quantity { get; set; }

        public virtual Desserts Dessert { get; set; }
        public virtual DessertCarts DessertCart { get; set; }
    }
}