// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class DessertImages
    {
        public int ImageId { get; set; }
        public int? DessertId { get; set; }
        public string DessertImageName { get; set; }

        public virtual Desserts Dessert { get; set; }
    }
}