// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class DessertCarts
    {
        public DessertCarts()
        {
            DessertCartItems = new HashSet<DessertCartItems>();
        }

        public int Id { get; set; }
        public string MemberName { get; set; }

        public virtual Members MemberNameNavigation { get; set; }
        public virtual ICollection<DessertCartItems> DessertCartItems { get; set; }
    }
}