// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Discounts
    {
        public int DiscountId { get; set; }
        public int DessertId { get; set; }
        public int DiscountPrice { get; set; }
        public DateTime StartAt { get; set; }
        public DateTime EndAt { get; set; }

        public virtual Desserts Dessert { get; set; }
    }
}