// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class DiscountGroup
    {
        public DiscountGroup()
        {
            Coupons = new HashSet<Coupon>();
            DiscountGroupItems = new HashSet<DiscountGroupItem>();
        }

        public int DiscountGroupId { get; set; }
        public string DiscountGroupName { get; set; }

        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual ICollection<DiscountGroupItem> DiscountGroupItems { get; set; }
    }
}