// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class DiscountGroupItem
    {
        public int DiscountGroupItemId { get; set; }
        public int DiscountGroupId { get; set; }
        public int DessertId { get; set; }

        public virtual Dessert Dessert { get; set; }
        public virtual DiscountGroup DiscountGroup { get; set; }
    }
}