// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class DiscountGroups
    {
        public DiscountGroups()
        {
            Coupons = new HashSet<Coupons>();
            DiscountGroupItems = new HashSet<DiscountGroupItems>();
        }

        public int DiscountGroupId { get; set; }
        public string DiscountGroupName { get; set; }

        public virtual ICollection<Coupons> Coupons { get; set; }
        public virtual ICollection<DiscountGroupItems> DiscountGroupItems { get; set; }
    }
}