// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Employees
    {
        public Employees()
        {
            Role = new HashSet<Roles>();
        }

        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public string EncryptedPassword { get; set; }
        public DateTime CreateAt { get; set; }
        public string ImageName { get; set; }

        public virtual ICollection<Roles> Role { get; set; }
    }
}