// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class LessonCategory
    {
        public LessonCategory()
        {
            Lessons = new HashSet<Lesson>();
        }

        public int LessonCategoryId { get; set; }
        public string LessonCategoryName { get; set; }

        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}