// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class LessonOrders
    {
        public LessonOrders()
        {
            LessonOrderDetails = new HashSet<LessonOrderDetails>();
        }

        public int LessonOrderId { get; set; }
        public int MemberId { get; set; }
        public int LessonOrderStatusId { get; set; }
        public int? CouponId { get; set; }
        public DateTime CreateTime { get; set; }
        public int LessonOrderTotal { get; set; }
        public string Note { get; set; }
        public string OrderCancellationReason { get; set; }
        public string DiscountInfo { get; set; }

        public virtual Coupons Coupon { get; set; }
        public virtual OrderStatuses LessonOrderStatus { get; set; }
        public virtual Members Member { get; set; }
        public virtual ICollection<LessonOrderDetails> LessonOrderDetails { get; set; }
    }
}