// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class LessonImages
    {
        public int LessonImageId { get; set; }
        public int LessonId { get; set; }
        public string LessonImageName { get; set; }

        public virtual Lessons Lesson { get; set; }
    }
}