// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class LessonOrder
    {
        public LessonOrder()
        {
            LessonOrderDetails = new HashSet<LessonOrderDetail>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        public int LessonOrderStatusId { get; set; }
        public int? CouponId { get; set; }
        public DateTime CreateTime { get; set; }
        public int LessonOrderTotal { get; set; }
        public string Note { get; set; }
        public string OrderCancellationReason { get; set; }
        public string DiscountInfo { get; set; }

        public virtual Coupon Coupon { get; set; }
        public virtual OrderStatus LessonOrderStatus { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<LessonOrderDetail> LessonOrderDetails { get; set; }
    }
}