// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Members
    {
        public Members()
        {
            DessertOrders = new HashSet<DessertOrders>();
            LessonOrders = new HashSet<LessonOrders>();
            MemberCoupons = new HashSet<MemberCoupons>();
        }

        public int Id { get; set; }
        public string MemberName { get; set; }
        public string Email { get; set; }
        public string EncryptedPassword { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public DateTime CreateAt { get; set; }
        public DateTime Birth { get; set; }
        public bool Gender { get; set; }
        public string ImageName { get; set; }
        public bool IsBan { get; set; }
        public int CancelTimes { get; set; }
        public bool? DailyGamePlayed { get; set; }
        public bool? WeeklyGamePlayed { get; set; }

        public virtual DessertCarts DessertCarts { get; set; }
        public virtual ICollection<DessertOrders> DessertOrders { get; set; }
        public virtual ICollection<LessonOrders> LessonOrders { get; set; }
        public virtual ICollection<MemberCoupons> MemberCoupons { get; set; }
    }
}