// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Member
    {
        public Member()
        {
            DessertOrders = new HashSet<DessertOrder>();
            LessonOrders = new HashSet<LessonOrder>();
            MemberCoupons = new HashSet<MemberCoupon>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string EncryptedPassword { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public DateTime CreateAt { get; set; }
        public DateTime? Birth { get; set; }
        public bool? Gender { get; set; }
        public string ImageName { get; set; }
        public bool? IsBan { get; set; }
        public int CancelTimes { get; set; }
        public bool? IsConfirmed { get; set; }
        public string ConfirmCode { get; set; }
        public bool? DailyGamePlayed { get; set; }
        public bool? WeeklyGamePlayed { get; set; }

        public virtual DessertCart DessertCart { get; set; }
        public virtual ICollection<DessertOrder> DessertOrders { get; set; }
        public virtual ICollection<LessonOrder> LessonOrders { get; set; }
        public virtual ICollection<MemberCoupon> MemberCoupons { get; set; }
    }
}