// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class OrderStatuses
    {
        public OrderStatuses()
        {
            DessertOrders = new HashSet<DessertOrders>();
            LessonOrders = new HashSet<LessonOrders>();
        }

        public int OrderStatusId { get; set; }
        public string StatusName { get; set; }

        public virtual ICollection<DessertOrders> DessertOrders { get; set; }
        public virtual ICollection<LessonOrders> LessonOrders { get; set; }
    }
}