// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Permissions
    {
        public Permissions()
        {
            Role = new HashSet<Roles>();
        }

        public int Id { get; set; }
        public string PermissionName { get; set; }

        public virtual ICollection<Roles> Role { get; set; }
    }
}