// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Promotions
    {
        public int PromotionId { get; set; }
        public int? CouponId { get; set; }
        public string PromotionImage { get; set; }
        public string PromotionName { get; set; }
        public string Description { get; set; }
        public DateTime LaunchAt { get; set; }
        public DateTime StartAt { get; set; }
        public DateTime EndAt { get; set; }
        public DateTime CreateAt { get; set; }

        public virtual Coupons Coupon { get; set; }
    }
}