// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Roles
    {
        public Roles()
        {
            Employee = new HashSet<Employees>();
            Permission = new HashSet<Permissions>();
        }

        public int Id { get; set; }
        public string RoleName { get; set; }
        public string RoleDisplayName { get; set; }

        public virtual ICollection<Employees> Employee { get; set; }
        public virtual ICollection<Permissions> Permission { get; set; }
    }
}