// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Role
    {
        public Role()
        {
            Employees = new HashSet<Employee>();
            Permissions = new HashSet<Permission>();
        }

        public int Id { get; set; }
        public string RoleName { get; set; }
        public string RoleDisplayName { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}