// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Specification
    {
        public Specification()
        {
            DessertCartItems = new HashSet<DessertCartItem>();
        }

        public int SpecificationId { get; set; }
        public int? DessertId { get; set; }
        public string Flavor { get; set; }
        public string Size { get; set; }
        public int UnitPrice { get; set; }

        public virtual Dessert Dessert { get; set; }
        public virtual ICollection<DessertCartItem> DessertCartItems { get; set; }
    }
}