// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIERRA_Server.Models.EFModels
{
    public partial class Teachers
    {
        public Teachers()
        {
            Lessons = new HashSet<Lessons>();
        }

        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public string TeacherImage { get; set; }
        public string Specialty { get; set; }
        public string Experience { get; set; }
        public string License { get; set; }
        public string Academic { get; set; }
        public bool TeacherStatus { get; set; }

        public virtual ICollection<Lessons> Lessons { get; set; }
    }
}